In [8]:
import pandas as pd
City=['Bursa', 
      'İzmir', 
      'Ankara',
      'Aydın' , 
      'Antalya' ,
      'İstanbul' ,
      'Eskişehir']
Population=[3186291,
            4455294,
            5747325,
            1134031,
            2619832,
            16034511,
            907353]
Area=[10820000,
      11891000,
      24521000,
      1582000,
      1417000,
      5343000,
      2678000]
pd.DataFrame({'City':City,'Population':Population,'Area':Area})

        City  Population      Area
0      Bursa     3186291  10820000
1      İzmir     4455294  11891000
2     Ankara     5747325  24521000
3      Aydın     1134031   1582000
4    Antalya     2619832   1417000
5   İstanbul    16034511   5343000
6  Eskişehir      907353   2678000